spring.application.name=Booking_System_Practice

spring.datasource.url=jdbc:postgresql://localhost:5433/bookingdb
spring.datasource.username=booking
spring.datasource.password=booking_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=86400000

